# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3056d864e8e990ac47df6002395be34fcc6b35145487e15dc030d02b5fd4a8cf0ff35c5442b8fd5614ae7c94ac6a0e9befa04214b629e785411da84ec77f51a8

test:
  secret_key_base: 7706b374ad6153f181897a942e3d75866905b882958c5a7145805acadf89fe9da095801b4631487168b848c5fe3cc9077ebb73311b563f489b79480d97e2d699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
